### ISSUE TITLE
Issue in updated version of google re-captcha

### ISSUE THREAD

**Issue by zapbuild007** [leewinder/ng2-google-recaptcha#10]
When i have updated ng-google-recaptcha@1.2.0 then i have faced following issue:

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /var/www/html/ifta/trunk/frontend/node_modules/ng2-google-recaptcha/node_modules/@angular/core/core.d.ts, resolving symbol RecaptchaModule in /var/www/html/ifta/trunk/frontend/node_modules/ng2-google-recaptcha/module/recaptcha.module.ts, resolving symbol RecaptchaModule in /var/www/html/ifta/trunk/frontend/node_modules/ng2-google-recaptcha/module/recaptcha.module.ts

**Comment by kue-bano** [comment]
Try deleting your node modules folder and run "npm install"

**Comment by kkpenas** [comment]
I still encounter this issue, even after npm install
On ng serve it works, but ng build breaks and display this error.


ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /myproject/node_modules/ng2-google-recaptcha/node_modules/@angular/core/core.d.ts, resolving symbol RecaptchaModule in /myproject/node_modules/ng2-google-recaptcha/module/recaptcha.module.ts, resolving symbol RecaptchaModule in /myproject/node_modules/ng2-google-recaptcha/module/recaptcha.module.ts
at positionalError (/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:25266:35)
at simplifyInContext (/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:25109:27)
at StaticReflector.simplify (/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:25123:13)
at StaticReflector.annotations (/myproject/node_modules/@angular/compiler/bundles/compiler.umd.js:24553:41)
at _getNgModuleMetadata (/myproject/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
at _extractLazyRoutesFromStaticModule (/myproject/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
at /myproject/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
at Array.reduce (native)
at _extractLazyRoutesFromStaticModule (/myproject/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
at Object.listLazyRoutesOfModule (/myproject/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/myproject/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
at AotPlugin._getLazyRoutesFromNgtools (/myproject/node_modules/@ngtools/webpack/src/plugin.js:207:44)
at _donePromise.Promise.resolve.then.then.then.then.then (/myproject/node_modules/@ngtools/webpack/src/plugin.js:443:24)
at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by leewinder** [comment]
This should _hopefully_ be resolved in v5.0.0
